"""initial tables

Revision ID: 1a957fb669cf
Revises: 
Create Date: 2026-05-09 11:46:02.884281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a957fb669cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_type', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('memory_type', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('emotional_valence', sa.Float(), nullable=True),
    sa.Column('emotional_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('symbolic_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('related_robot_ids', sa.ARRAY(sa.Uuid()), nullable=True),
    sa.Column('related_user_id', sa.Uuid(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_accessed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('object_name', sa.Text(), nullable=True),
    sa.Column('object_description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('symbolic_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('robot_reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('object_type', sa.Text(), nullable=True),
    sa.Column('object_id', sa.Uuid(), nullable=True),
    sa.Column('relationship_type', sa.Text(), nullable=True),
    sa.Column('intimacy', sa.Float(), nullable=False),
    sa.Column('trust', sa.Float(), nullable=False),
    sa.Column('tension', sa.Float(), nullable=False),
    sa.Column('jealousy', sa.Float(), nullable=False),
    sa.Column('understanding', sa.Float(), nullable=False),
    sa.Column('history_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('birth_place', sa.Text(), nullable=True),
    sa.Column('origin_story', sa.Text(), nullable=True),
    sa.Column('core_desire', sa.Text(), nullable=True),
    sa.Column('core_fear', sa.Text(), nullable=True),
    sa.Column('personality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('speaking_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('voice_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_emotion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_type', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('sender_name', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('emotion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yearly_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('robot_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('memory_title', sa.Text(), nullable=True),
    sa.Column('memory_content', sa.Text(), nullable=True),
    sa.Column('emotional_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personality_effect', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('symbolic_tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yearly_memories')
    op.drop_table('messages')
    op.drop_table('robots')
    op.drop_table('relationships')
    op.drop_table('object_observations')
    op.drop_table('memories')
    op.drop_table('conversations')
    op.drop_table('users')
    # ### end Alembic commands ###
