"""add memory strength and importance to yearly_memories

Revision ID: 39c38b95bc32
Revises: 1a957fb669cf
Create Date: 2026-05-09 11:58:53.385612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c38b95bc32'
down_revision: Union[str, Sequence[str], None] = '1a957fb669cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yearly_memories', sa.Column('importance', sa.Float(), nullable=True))
    op.add_column('yearly_memories', sa.Column('memory_strength', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yearly_memories', 'memory_strength')
    op.drop_column('yearly_memories', 'importance')
    # ### end Alembic commands ###
