"""add relationships_snapshot to robots

Revision ID: 57fbf61d4fcf
Revises: 66c72ef2d99a
Create Date: 2026-05-11 14:10:40.229455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57fbf61d4fcf'
down_revision: Union[str, Sequence[str], None] = '66c72ef2d99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('relationships_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robots', 'relationships_snapshot')
    # ### end Alembic commands ###
