"""add memory evolution fields

Revision ID: 5ee4eb5eea8e
Revises: 478c3b9ab018
Create Date: 2026-05-10 01:52:52.722279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee4eb5eea8e'
down_revision: Union[str, Sequence[str], None] = '478c3b9ab018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('base_importance', sa.Float(), nullable=True))
    op.add_column('memories', sa.Column('last_activated', sa.TIMESTAMP(), nullable=True))
    op.add_column('memories', sa.Column('activation_count', sa.Integer(), nullable=True))
    op.add_column('memories', sa.Column('reinterpretation', sa.Text(), nullable=True))
    op.add_column('memories', sa.Column('linked_memory_ids', sa.ARRAY(sa.Uuid()), nullable=True))
    op.add_column('memories', sa.Column('memory_source', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'memory_source')
    op.drop_column('memories', 'linked_memory_ids')
    op.drop_column('memories', 'reinterpretation')
    op.drop_column('memories', 'activation_count')
    op.drop_column('memories', 'last_activated')
    op.drop_column('memories', 'base_importance')
    # ### end Alembic commands ###
