"""add batch_index to yearly_memories

Revision ID: 66c72ef2d99a
Revises: d82eedec33e0
Create Date: 2026-05-11 13:05:33.511602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c72ef2d99a'
down_revision: Union[str, Sequence[str], None] = 'd82eedec33e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yearly_memories', sa.Column('batch_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yearly_memories', 'batch_index')
    # ### end Alembic commands ###
