"""add desktop_visible to robots

Revision ID: 9346fcfb1039
Revises: ae36e5831db0
Create Date: 2026-05-30 17:32:31.844552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9346fcfb1039'
down_revision: Union[str, Sequence[str], None] = 'ae36e5831db0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('desktop_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robots', 'desktop_visible')
    # ### end Alembic commands ###
