"""add energy field

Revision ID: a0e12534ebb0
Revises: 5ee4eb5eea8e
Create Date: 2026-05-10 09:57:36.561975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e12534ebb0'
down_revision: Union[str, Sequence[str], None] = '5ee4eb5eea8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('energy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robots', 'energy')
    # ### end Alembic commands ###
