"""add_asset_versions_table

Revision ID: ae36e5831db0
Revises: f87721d7f0c2
Create Date: 2026-05-27 14:33:20.933006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae36e5831db0'
down_revision: Union[str, Sequence[str], None] = 'f87721d7f0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('robot_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.Text(), nullable=False),
    sa.Column('asset_key', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_versions')
    # ### end Alembic commands ###
