"""add portrait stats memory fields

Revision ID: ddb2efa88136
Revises: 39c38b95bc32
Create Date: 2026-05-09 21:01:39.700556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddb2efa88136'
down_revision: Union[str, Sequence[str], None] = '39c38b95bc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('portrait', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('robots', sa.Column('generation_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('yearly_memories', sa.Column('memory_summary', sa.Text(), nullable=True))
    op.add_column('yearly_memories', sa.Column('memory_type', sa.Text(), nullable=True))
    op.add_column('yearly_memories', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('yearly_memories', sa.Column('generation_time_ms', sa.Integer(), nullable=True))
    op.add_column('yearly_memories', sa.Column('generation_cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yearly_memories', 'generation_cost_usd')
    op.drop_column('yearly_memories', 'generation_time_ms')
    op.drop_column('yearly_memories', 'word_count')
    op.drop_column('yearly_memories', 'memory_type')
    op.drop_column('yearly_memories', 'memory_summary')
    op.drop_column('robots', 'generation_stats')
    op.drop_column('robots', 'portrait')
    # ### end Alembic commands ###
