"""add robot_skills table

Revision ID: f87721d7f0c2
Revises: 57fbf61d4fcf
Create Date: 2026-05-11 16:23:18.156205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87721d7f0c2'
down_revision: Union[str, Sequence[str], None] = '57fbf61d4fcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robot_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('robot_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_keywords', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('execution_prompt', sa.Text(), nullable=True),
    sa.Column('skill_type', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robot_skills')
    # ### end Alembic commands ###
